carro/urls.py
from django.urls import path, include
from . import views
app_name='carro'

urlpatterns = [
    path('agregar/<int:producto_id>', views.agregar_producto, name="agregar"),
    path('eliminar/<int:producto_id>', views.eliminar_producto, name="eliminar"),
    path('sumar/<int:producto_id>', views.sumar_producto, name="sumar"),
    path('restar/<int:producto_id>', views.restar_producto, name="restar"),
    path('limpiar/', views.limpiar_carro, name="limpiar"),
    path('carro/', views.template_carro, name="tCarro"),
    path('pago/', views.pago, name='pago')
]

productos/urls.py
# urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static 
from .views import ProductosCrud

app_name = 'Productos'

urlpatterns = [
    path('productos/', views.productos, name="tProductos"),

    path('prodsAdmin/', ProductosCrud.viewAdminProds, name="prodsAdmin"),
    path('add/', ProductosCrud.agregarProd, name="add"),
    path('updated/<int:id>/', ProductosCrud.updatedProd, name='updatedProd'),
    path('<int:id>/', ProductosCrud.delateProd, name='delateProd'),

    path('categorias/', ProductosCrud.viewCateg, name="categorias"),
    path('addCateg/', ProductosCrud.addCateg, name="addCateg"),
    path('updatedCateg/<int:id>/', ProductosCrud.updatedCateg, name="updatedCateg"),
    path('categoria/<int:id>/', ProductosCrud.delateCateg, name="delateCateg"),

    path('marcas/', ProductosCrud.viewMarc, name="marcas"),
    path('addMarca/', ProductosCrud.addMarca, name="addMarca"),
    path('updatedMarca/<int:id>/', ProductosCrud.updatedMarca, name="updatedMarca"),
    path('marca/<int:id>/', ProductosCrud.delateMarca, name="delateMarca"),

    path('slide/', views.promocion, name="promocion")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectTuMercadoALaMano/urls.py
from django.contrib import admin
from django.urls import path, include
from paypal.standard.ipn import urls as paypal_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls')),
    path('', include('productos.urls')),
    path('', include('carro.urls')),
    path('', include('usuario.urls')),
    path('', include('contacto.urls')),
    path('', include('reportes.urls')),
    path('', include('appAdmin.urls')),
    path('', include('paypal.standard.ipn.urls')),
    path('', include('pasarelaPago.urls')),
    path('paypal/', include(paypal_urls))
]

productos/models.py
from django.db import models
from django.utils import timezone

class Categoria(models.Model):
    categoria = models.CharField(max_length=20)
    imagen = models.ImageField(upload_to='productos/')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.categoria
    

class Marca(models.Model):
    marca = models.CharField(max_length=25, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'marca'
        verbose_name_plural = 'marcas'

    def __str__(self):
        return self.marca



class Producto(models.Model):
    nombre = models.CharField(max_length=25)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    precio_anterior = models.CharField(max_length=50, blank=True, null=True)
    precio = models.CharField(max_length=50)
    stock = models.IntegerField()
    descripcion = models.TextField(blank=True, null=True)
    fecha_vencimiento = models.DateField()
    imagen = models.ImageField(upload_to='productos/')
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True, blank=True)

    class Meta:
        verbose_name = 'producto'
        verbose_name_plural = 'productos'
    
    def __str__(self):
        return self.nombre
    
    # Metodo para actualizar el stock.
    def actualizar_stock(self, cantidad):
        self.stock -= cantidad
        self.save()
    
class Promocion(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    imagen = models.ImageField()
    imagen2 = models.ImageField(blank=True)
    imagen3 = models.ImageField(blank=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    descuento = models.IntegerField()
    fechaTermino = models.DateField()

    class Meta:
        verbose_name = 'Promocion'
        verbose_name_plural = 'Promociones'

    def vigente(self):
        return timezone.now().date() <= self.fechaTermino
    
    def __str__(self):
        return f"Promoción #{self.id} - Descuento: {self.descuento}% - Producto: {self.producto.nombre}"

productos/forms.py
from django import forms 
from .models import Producto, Categoria, Marca

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'marca', 'categoria', 'precio_anterior', 'precio', 'stock', 'descripcion', 'fecha_vencimiento', 'imagen']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'nombre', 'placeholder': 'Nombre'}),
            # 'marca': forms.TextInput(attrs={'class': 'marca', 'placeholder': 'Marca'}),
            # 'categoria': forms.TextInput(attrs={'class': 'categoria', 'placeholder': 'Categoría'}),
            'precio_anterior': forms.NumberInput(attrs={'class': 'precio_anterior', 'placeholder': 'Precio anterior'}),
            'precio': forms.NumberInput(attrs={'class': 'precio', 'placeholder': 'Precio'}),
            'stock': forms.TextInput(attrs={'class': 'stock', 'placeholder': 'Stock'}),
            'descripcion': forms.TextInput(attrs={'class': 'descripcion', 'placeholder': 'Descripción'}),
            'fecha_vencimiento': forms.DateInput(attrs={'class': 'fecha_vencimiento', 'placeholder': 'Fecha de vencimiento'}),
            'imagen': forms.ClearableFileInput(attrs={'class': 'imagen', 'placeholder': 'Imagen'}),
        }
        
class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['categoria', 'imagen']
        widgets = {
            'imagen': forms.ClearableFileInput(attrs={'class': 'imagen1', 'placeholder': 'Imagen'}),
        }

class MarcaForm(forms.ModelForm):
    class Meta:
        model = Marca
        fields = ['marca']

productos/views.py
from django.shortcuts import render,redirect, get_object_or_404
from productos.models import Producto, Categoria, Marca, Promocion
#
from django.db.models import Q
# Librerias oara el CRUD  del admin
from .forms import ProductoForm, CategoriaForm, MarcaForm

import os
#
from django.contrib import messages

# Librerias para verificar si el de la sesion es super user.
from django.contrib.auth.decorators import user_passes_test
from appAdmin.views import is_superuser

def productos(request):
    categorias = Categoria.objects.all()
    query = request.GET.get('query', '')  # Captura el valor del parámetro de búsqueda
    if query:
        products = Producto.objects.filter(
            Q(nombre__icontains=query) |  # Busca productos cuyo nombre contiene la consulta
            Q(marca__marca__icontains=query) |  # Busca productos cuya marca contiene la consulta
            Q(categoria__categoria__icontains=query)  # Busca productos cuya categoría contiene la consulta
        ).exclude(precio_anterior='')  # Excluye productos sin precio anterior
    else:
        products = Producto.objects.filter(precio_anterior__isnull=False).exclude(precio_anterior='')  # Filtra productos con precio anterior
    return render(request, 'productos.html', {'productos': products, 'query': query, 'categorias': categorias})
class ProductosCrud():
    # PRODUCTOS
    @user_passes_test(is_superuser)
    def viewAdminProds(request):
        query = request.GET.get('query', '')
        if query:
            products = Producto.objects.filter(
                Q(nombre__icontains=query) |  # Busca productos cuyo nombre contiene la consulta
                Q(marca_marca_icontains=query) |  # Busca productos cuya marca contiene la consulta
                Q(categoria_categoria_icontains=query) # Busca productos cuya categoría contiene la consulta
            )# Filtra productos que contienen el término de búsqueda en nombre, marca o categoría
        else: 
            products = Producto.objects.all()
        return render(request, 'productosAdmin.html', {'productos':products, 'query':query})
    def agregarProd(request):
        if request.method == 'POST':
            form = ProductoForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                messages.success(request, "Se ha guardado la información correctamente")
                return redirect('Productos:prodsAdmin')
            else:
                messages.error(request, "Hubo un error, revisa la información e intenta de nuevo.")
                form = ProductoForm()
        else:
            form = ProductoForm()
        return render(request, 'crudProds/addProduct.html', {'form' : form})
    def updatedProd(request, id):
        try:
            product = Producto.objects.get(pk=id) # Se debe obtener el producto por la 'clave primaria' (id)
        except Producto.DoesNotExist:
            return redirect('Productos:prodsAdmin')
        
        if request.method == 'POST':
            form = ProductoForm(request.POST, request.FILES, instance=product)
            if len(request.FILES) != 0:
                if len(product.imagen) > 0:
                    os.remove(product.imagen.path)
            if form.is_valid():
                form.save()
                messages.success(request, "Se ha actualizado la información correctamente.")
                return redirect('Productos:prodsAdmin')
        else:
            form = ProductoForm(instance=product) # Pre-popula el formulario con los datos del producto

        return render(request, 'crudProds/updatedProd.html', {'form': form})
    def delateProd(request, id):
        product = get_object_or_404(Producto, pk=id)
        if product.imagen and os.path.isfile(product.imagen.path):
            os.remove(product.imagen.path)

        product.delete()
        messages.success(request, "El producto se ha eliminado correctamente.")
        return redirect('Productos:prodsAdmin')
    
    # CATEGORÍA
    def viewCateg(request):
        categorias = Categoria.objects.all()
        context = {'categorias':categorias}
        return render(request, 'categorias/categorias.html', context)
    def addCateg(request):
        if request.method == 'POST':
            form = CategoriaForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                messages.success(request, "La categoría se agrego correctamente.")
                return redirect('Productos:categorias')
            else:
                messages.error(request, "Hubo un error con la información, intentalo de nuevo.")
                form = CategoriaForm()
        else:
            form = CategoriaForm()
        return render(request, 'categorias/addCateg.html', {'form':form})
   
    def updatedCateg(request, id):
        try:
            categoria = Categoria.objects.get(pk=id)
        except Marca.DoesNotExist:
            return redirect('Productos:categorias')       
        if request.method == 'POST':
            form = CategoriaForm(request.POST, request.FILES,instance=categoria)
            if len(request.FILES) != 0:
                if len(categoria.imagen) > 0:
                    os.remove(categoria.imagen.path)
            if form.is_valid():
                messages.success(request, "Se actualizó correctamente la información.")
                form.save()
                return redirect('Productos:categorias')
            else:
                messages.error(request, "Hubo un error, verifica la información e intenta de nuevo.")
        else:
            form = CategoriaForm(instance=categoria)
        return render(request, 'categorias/addCateg.html', {'form':form})
    def delateCateg(request, id):
        categoria = get_object_or_404(Categoria, pk=id)
        
        categoria.delete()
        messages.success(request, "Se eliminó correctamente la categoría.")
        return redirect('Productos:categorias')

    # MARCA.
    def viewMarc(request):
        marcas = Marca.objects.all()
        context = {'marcas':marcas}
        return render(request, 'marcas/marcas.html', context)
    def addMarca(request):
        if request.method == 'POST':
            form = MarcaForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "La marca se agrego correctamente.")
                return redirect('Productos:marcas')
            else:
                messages.error(request, "Hubo un error con la información, intentalo de nuevo.")
                form = MarcaForm()
        else:
            form = MarcaForm()
        return render(request, 'marcas/addMarca.html', {'form':form})
    def updatedMarca(request, id):
        try:
            marca = Marca.objects.get(pk=id)
        except Marca.DoesNotExist:
            return redirect('Productos:marcas')
        
        if request.method == 'POST':
            form = MarcaForm(request.POST, instance=marca)
            if form.is_valid():
                messages.success(request, "Se actualizó correctamente la información.")
                form.save()
                return redirect('Productos:marcas')
            else:
                messages.error(request, "Hubo un error, verifica la información e intenta de nuevo.")
        else:
            form = MarcaForm(instance=marca)
        return render(request, 'marcas/addMarca.html', {'form':form})
    def delateMarca(request, id):
        marca = get_object_or_404(Marca, pk=id)
        
        marca.delete()
        messages.success(request, "Se eliminó correctamente la marca.")
        return redirect('Productos:marcas')

def promocion(request):
    promociones = Promocion.objects.all()
    return render(request, 'promocion.html', {'promociones': promociones})

productos/templates/productos/marcas/addMarca.html
{% extends 'nav_foot.html' %}
{% load static %}

{% block title %}Agregar marca{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
<style>
    /* Estilos para el formulario */
    form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #f9f9f9;
    }

    form h1 {
        text-align: center;
        margin-bottom: 20px;
    }

    form button {
        background-color: #3e277e;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
        font-size: 16px;
    }

    form button:hover {
        background-color: #3e277e;
    }

    /* Estilos para los campos del formulario */
    form input[type=text],
    form input[type=email],
    form textarea {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 3px;
        font-size: 14px;
    }

    form textarea {
        height: 100px;
    }
    h1{
            text-align: center;
            font-weight: normal;
    }
</style>

<h1>Agregar Marca</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
{% endblock %}

productos/templates/productos/marcas/marcas.html
{% extends 'nav_foot.html' %}

{% load static %}

{% block title %}Marcas{% endblock %}

{% block header %}{% endblock %}

{% block content %}
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            
            <!-- messages -->
            {% if messages %}
                <div class="alert alert-dimissible fade show" role="alert">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dimissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            <a href="{% url 'Productos:prodsAdmin' %}" class="btn btn-purple">Productos</a>
            <a href="{% url 'Productos:categorias' %}" class="btn btn-purple">Categorías</a> <br> <br>
            
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                <div class="col mb-5">
                    <div class="card h-100">
                        <table class="table table-striped">
                            <thead style="text-align: center;">
                                <a href="{% url 'Productos:addMarca' %}" class="btn btn-purple btn-sm">Agregar marca</a>
                                <tr>
                                    <th scope="col">Marcas</th>
                                    <th scope="col">Acciones</th>
                                </tr>
                            </thead>
                            {% for marc in marcas %}
                                <tbody style="text-align: center;">
                                    <tr>
                                        <td>{{marc.marca}}</td>
                                        <td>
                                            <!-- Product actions-->
                                            <a href="{% url 'Productos:updatedMarca' marc.id %}" class="btn btn-warning btn-sm">Editar</a>
                                            <a href="#" onclick="confirmDelete('{{ marc.id }}')" class="btn btn-danger btn-sm">Eliminar</a>
                                        </td>
                                    </tr>
                                </tbody>
                            {% endfor %}
                        </table>
                    </div>
                </div>   
            </div>   

        </div>   
    </section>
    
    <style>
        .btn-purple {
      background-color: #4E319B;
      color: white;
    }
    </style>

<!-- configuracion de alerta con sweetalert2 -->

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<!-- Script para confirmación de eliminación -->
    <script>
    function confirmDelete(marcaId) {
        Swal.fire({
            title: "¿Estás seguro?",
            text: "No podrás revertir esto.",
            icon: "warning",
            showCancelButton: true,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Confirmar",
            cancelButtonText: "Cancelar"
        }).then((result) => {
            if (result.isConfirmed) {
                // Redirigir a la URL de eliminación
                window.location.href = "{% url 'Productos:delateMarca'  0 %}".replace('0', marcaId);
            }
        });
    }
    </script>
{% endblock %}